name: NodeJS Application Build

on:
  - push

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
    - name: Checkout NodeJS App
      uses: actions/checkout@v2
    
    - name: Setup NodeJS On Worker Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.0'
    
    - name: Install & Test
      run: |
        npm install
        npm test

    # - name: Login to DockerHub
    #   run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # - name: Build docker images
    #   run: |
    #     echo ---Building and starting up docker---
    #     docker-compose -f ./ciwithgithub/docker-compose.yml -p testing up -d
    #     echo ---Containers up---