name: NodeJS Application Build

on:
  - push

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
    - name: Checkout NodeJS App
      uses: actions/checkout@v2
    
    - name: Setup NodeJS On Worker Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.0'
    
    - name: Install & Test
      run: |
        npm install
        npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout The Repo
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: shehuawwal/nodejs-app
  
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}